import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 300px;
    height: 400px;

    callback LoginClick();

    Text {
        text: "ArabRust Cheat Check";
        width: 250px;
        y: 200px; height: 100px;
        horizontal-alignment: TextHorizontalAlignment.center;
        font-size: 20px;
        font-weight: 900;
        color: red;
    }

    Image {
        source: @image-url("../src/Images/ArabRust.png");
        width: 100px;
        y: 90px; height: 100px;
        horizontal-alignment: ImageHorizontalAlignment.center;
        image-rendering: ImageRendering.smooth;
    }

    Button {
        text: "Login";
        width: 150px;
        x: 77px;
        y: 250px;

        clicked => {
            root.LoginClick();
        }
    }
}
